#!/usr/bin/env bash
# script that configure a new ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service start nginx
