#!/usr/bin/env bash
#script that install nginx on a remote server and configure it


#update packages list and install nginx
sudo apt-get update
sudo apt-get install nginx -y

sudo sed -i 's/listen/s*80;/listen 80 default_server;/g' /etc/nginx/sites_available/default

sudo /etc/init.d/nginx restart

sudo echo "Hello World!" | sudo tee /var/www/html/index.html
