#!/usr/bin/env bash
#  script that configures a new Ubuntu machine to run on the server itself

sudo apt-get install nginx -y

sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo sh -c "echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        return 200 \"Hello World!\";
    }
}' > /etc/nginx/sites-available/default"

sudo service nginx restart

