#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites_available/default

sudo /etc/init.d/nginx restart
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
