#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

apt-get update
apt-get -y install nginx

sudo sed -i "/^}/i \
\
  location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
  }" /etc/nginx/nginx.conf
sudo /etc/init.d/nginx restart
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
