#!/usr/bin/env bash
# configure haproxy

sudo apt-get update
sudo apt-get install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
# Configure frontend
frontend myfrontend
  bind *:80
  default_backend mybackend

# Configure backend
backend mybackend
  balance roundrobin
  server 181356-web-01 18.206.233.250:80
  server 181356-web-02 34.239.255.79:80
EOT
