#!/usr/bin/env bash
# script that configures a servers
sudo apt update
sudo apt install -y nginx

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart

sudo ufw allow 80
