#!/usr/bin/env bash
# script that configures a server
sudo apt update
sudo apt install -y nginx

sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

sudo service restart nginx

sudo ufw allow 80
